# Generated by Django 3.2.14 on 2022-07-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_emailindentefication_slug_indentefication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailindentefication',
            name='slug_indentefication',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
