# Generated by Django 3.2.14 on 2022-07-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailindentefication',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
